Add a new input flag to avoid commenting on stacks that have not changed.
corymhall/cdk-diff-action pull request #85
Opened 2024-09-26 18:11 UTC by drew-rsk

Adds a flag to allow users to skip comments for stacks that have not changed.

2024-09-27 09:54 UTC, corymhall requested changes
@drew-rsk overall the PR looks good! The only thing missing is adding the new input property to the action metadata here

https://github.com/corymhall/cdk-diff-action/blob/69475f7d7c6a41899707607282e33bc0ad01ed6f/.projenrc.ts#L23

I'm a little hesitant to add this feature as is because I'm worried that it creates a scenario where something could fail to process and the user would think that it was because the stack had no changes. 

What would you think about having a single summary comment that has info on what stages/stacks were processed? It could just be a single comment saying that stacks x,y,z had no changes.

2024-09-30 19:52 UTC, drew-rsk commented
> @drew-rsk overall the PR looks good! The only thing missing is adding the new input property to the action metadata here
> 
> https://github.com/corymhall/cdk-diff-action/blob/69475f7d7c6a41899707607282e33bc0ad01ed6f/.projenrc.ts#L23
> 
> I'm a little hesitant to add this feature as is because I'm worried that it creates a scenario where something could fail to process and the user would think that it was because the stack had no changes.
> 
> What would you think about having a single summary comment that has info on what stages/stacks were processed? It could just be a single comment saying that stacks x,y,z had no changes.

Q1: Yeah that'd be a good step and possibly sufficient for my team's development purposes.  How can I play with my changes as they are, or any other PR's changes, as a way to manually inspect the results?

Q2: I propose leaving this PR as is and working up an independent one that does what you suggest over hacking this one into a different functional solution.  How does that plan suit you?

2024-10-07 12:26 UTC, corymhall commented
> Q1: Yeah that'd be a good step and possibly sufficient for my team's development purposes. How can I play with my changes as they are, or any other PR's changes, as a way to manually inspect the results?

You can pin an action to a branch if you want to test. Something like this should work.

```yml
- name: Diff
        uses: corymhall/cdk-diff-action@drew-rsk:drew/ignore-unchanged-stacks
```

> Q2: I propose leaving this PR as is and working up an independent one that does what you suggest over hacking this one into a different functional solution. How does that plan suit you?

I'm not sure what you are asking here. I'm not comfortable merging this PR as is because I think we need to have some kind of indication that all stacks were processed.

2025-05-05 13:39 UTC, rantoniuk commented
> What would you think about having a single summary comment that has info on what stages/stacks were processed? It could just be a single comment saying that stacks x,y,z had no changes.

Right now it's actually unclear when the comment was generated/updated and it's only visible upon clicking the dropdown on the comment box.

I would say that the comment should look like this:

```
No changes detected. <--- only in case no stacks have a difference

Generated for commit X (timestamp) <--- added timestamp here
```

2025-05-06 09:24 UTC, corymhall commented
> I would say that the comment should look like this:

Yeah I think adding a timestamp makes sense

2025-05-06 09:30 UTC, closed without merging

2025-05-06 11:00 UTC, rantoniuk commented
Please re-open this - adding the timestamp does not fulfill/replace the need of the input for no stack changes.

2025-05-06 12:30 UTC, corymhall commented
@rantoniuk we currently _always_ comment with the status of each stack (with/without changes). This PR was wanting to remove commenting altogether when stacks have no changes which we are not going to do. There is an existing issue to track that request #86 which we can continue that discussion.